import {createSupabaseServerClient} from "@/lib/supabase/server";
import {connectGithub,createGithubRepository,generateStoreProject} from "./actions";
export default async function GithubPage(){
 const s=await createSupabaseServerClient();
 const {data:stores}=await s.from("stores").select("id,name,slug").order("created_at",{ascending:true}).limit(20);
 const store=stores?.[0];
 const {data:connection}=store?await s.from("github_connections").select("id,account_login,account_type,status,verified_at,permissions,last_error").eq("store_id",store.id).maybeSingle():{data:null};
 const {data:repo}=store?await s.from("github_repositories").select("id,full_name,default_branch,private,html_url").eq("store_id",store.id).maybeSingle():{data:null};
 return <section className="p-5 sm:p-8"><h1 className="text-2xl font-bold">GitHub Automation</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Connect a GitHub App installation, verify provider access, create a repository and generate the store project. Secrets are server-only.</p>
 <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Integration health</h2><p className="mt-1 text-sm text-slate-400">{connection?connection.account_login+" · "+connection.account_type:"No GitHub installation connected"}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{connection?.status==="connected"?"CONNECTED":connection?.status==="error"?"ERROR":"CONFIGURATION REQUIRED"}</span></div>
 {!connection&&store&&<form action={connectGithub} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="store_id" value={store.id}/><input name="installation_id" inputMode="numeric" placeholder="GitHub App installation ID" className="rounded-xl border border-white/10 bg-black/20 p-3"/><button className="rounded-xl bg-white px-4 font-semibold text-black">Verify & Connect</button></form>}
 {connection?.status==="connected"&&<p className="mt-4 text-xs text-emerald-300">Provider verification succeeded at {connection.verified_at?new Date(connection.verified_at).toLocaleString():""}.</p>}
 {connection?.last_error&&<p className="mt-3 text-xs text-red-300">{connection.last_error}</p>}</div>
 {connection?.status==="connected"&&store&&<div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Repository</h2>{repo?<><p className="mt-2 text-sm">{repo.full_name} · {repo.private?"Private":"Public"}</p><form action={generateStoreProject} className="mt-4"><input type="hidden" name="store_id" value={store.id}/><input type="hidden" name="repository_id" value={repo.id}/><button className="rounded-xl bg-cyan-300 px-4 py-2 font-semibold text-black">Generate / sync store project</button></form></>:<form action={createGithubRepository} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="store_id" value={store.id}/><input type="hidden" name="connection_id" value={connection.id}/><input name="name" placeholder={store.slug||"store-project"} className="rounded-xl border border-white/10 bg-black/20 p-3"/><select name="private" className="rounded-xl border border-white/10 bg-black/20 p-3"><option value="true">Private</option><option value="false">Public</option></select><button className="rounded-xl bg-white px-4 font-semibold text-black">Create repository</button></form>}</div>}
 <div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-slate-400"><p className="font-semibold text-white">Required GitHub App permissions</p><p className="mt-2">Metadata: read, Contents: write. Repository creation also requires Administration: write. Grant only the permissions needed for the enabled workflow.</p></div>
 </section>;
}
