"use server";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {revalidatePath} from "next/cache";
function text(v:FormDataEntryValue|null){return String(v??"").trim()}
function slug(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)}
function num(v:string){if(!v)return null;const n=Number(v);return Number.isFinite(n)?n:null}
async function client(){return createSupabaseServerClient()}
export async function createProduct(formData:FormData){const s=await client();const store_id=text(formData.get("store_id"));const name=text(formData.get("name"));if(!store_id||!name)throw new Error("Store and product name are required");const data={store_id,name,slug:slug(text(formData.get("slug"))||name),sku:text(formData.get("sku"))||null,description:text(formData.get("description"))||null,price:num(text(formData.get("price")))??0,compare_at_price:num(text(formData.get("compare_at_price"))),cost:num(text(formData.get("cost"))),stock:Math.max(0,Number(text(formData.get("stock"))||0)),brand:text(formData.get("brand"))||null,tags:text(formData.get("tags")).split(",").map(x=>x.trim()).filter(Boolean),weight:num(text(formData.get("weight"))),length:num(text(formData.get("length"))),width:num(text(formData.get("width"))),height:num(text(formData.get("height"))),hsn_code:text(formData.get("hsn_code"))||null,gst_rate:num(text(formData.get("gst_rate"))),video_url:text(formData.get("video_url"))||null,status:text(formData.get("status"))||"draft",seo:{title:text(formData.get("seo_title")),description:text(formData.get("seo_description"))}};const {error}=await s.from("products").insert(data);if(error)throw new Error(error.message);revalidatePath("/dashboard/products")}
export async function updateProduct(formData:FormData){const s=await client();const id=text(formData.get("id"));const store_id=text(formData.get("store_id"));if(!id||!store_id)throw new Error("Invalid product");const status=text(formData.get("status"))||"draft";const {error}=await s.from("products").update({name:text(formData.get("name")),slug:slug(text(formData.get("slug"))),sku:text(formData.get("sku"))||null,description:text(formData.get("description"))||null,price:num(text(formData.get("price")))??0,compare_at_price:num(text(formData.get("compare_at_price"))),cost:num(text(formData.get("cost"))),stock:Math.max(0,Number(text(formData.get("stock"))||0)),brand:text(formData.get("brand"))||null,tags:text(formData.get("tags")).split(",").map(x=>x.trim()).filter(Boolean),weight:num(text(formData.get("weight"))),length:num(text(formData.get("length"))),width:num(text(formData.get("width"))),height:num(text(formData.get("height"))),hsn_code:text(formData.get("hsn_code"))||null,gst_rate:num(text(formData.get("gst_rate"))),video_url:text(formData.get("video_url"))||null,status,published_at:status==="active"?new Date().toISOString():null,seo:{title:text(formData.get("seo_title")),description:text(formData.get("seo_description"))}}).eq("id",id).eq("store_id",store_id);if(error)throw new Error(error.message);revalidatePath("/dashboard/products");revalidatePath("/dashboard/products/"+id)}
export async function deleteProduct(formData:FormData){const s=await client();const {error}=await s.from("products").delete().eq("id",text(formData.get("id"))).eq("store_id",text(formData.get("store_id")));if(error)throw new Error(error.message);revalidatePath("/dashboard/products")}
export async function duplicateProduct(formData:FormData){const s=await client();const id=text(formData.get("id"));const store_id=text(formData.get("store_id"));const {data:p,error:e}=await s.from("products").select("*").eq("id",id).eq("store_id",store_id).single();if(e||!p)throw new Error(e?.message||"Product not found");const {id:_,created_at:__,updated_at:___,published_at:____,...copy}=p;copy.name=p.name+" Copy";copy.slug=p.slug+"-copy";copy.sku=p.sku?p.sku+"-COPY":null;copy.status="draft";const {error}=await s.from("products").insert(copy);if(error)throw new Error(error.message);revalidatePath("/dashboard/products")}
export async function bulkImportProducts(formData:FormData){const s=await client();const store_id=text(formData.get("store_id"));const csv=text(formData.get("csv"));if(!store_id||!csv)throw new Error("Store and CSV are required");const lines=csv.split(/\r?\n/).filter(Boolean);const rows=lines.slice(1).map(line=>line.split(",").map(x=>x.trim().replace(/^"|"$/g,""))).filter(r=>r[0]);const data=rows.map(r=>({store_id,name:r[0],slug:slug(r[1]||r[0]),sku:r[2]||null,price:Number(r[3]||0),stock:Math.max(0,Number(r[4]||0)),status:r[5]==="active"||r[5]==="archived"?r[5]:"draft",description:r[6]||null,brand:r[7]||null,tags:(r[8]||"").split("|").map(x=>x.trim()).filter(Boolean)}));const {error}=await s.from("products").insert(data);if(error)throw new Error(error.message);revalidatePath("/dashboard/products")}
