import {createSupabaseServerClient} from "@/lib/supabase/server";
import {startSupabaseProvisioning,processSupabaseProvisioning} from "./actions";
export default async function SupabasePage(){
 const s=await createSupabaseServerClient();
 const {data:stores}=await s.from("stores").select("id,name,slug").order("created_at",{ascending:true}).limit(20);
 const store=stores?.[0];
 const {data:project}=store?await s.from("supabase_projects").select("id,project_ref,project_name,region,status,project_url,last_verified_at,last_error,attempt_count,next_retry_at").eq("store_id",store.id).maybeSingle():{data:null};
 const configured=Boolean(process.env.SUPABASE_MANAGEMENT_API_TOKEN);
 return <section className="p-5 sm:p-8"><h1 className="text-2xl font-bold">Supabase Automation</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Provision a dedicated Supabase project, wait for healthy services, apply migrations, configure Auth and Storage, then verify provider state.</p>
 <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Integration health</h2><p className="mt-1 text-sm text-slate-400">{configured?"Management API configured":"Management API token not configured"}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{project?.status==="ready"?"CONNECTED":project?.status==="failed"?"ERROR":"CONFIGURATION REQUIRED"}</span></div>
 {!configured&&<p className="mt-4 text-xs text-amber-300">Required: SUPABASE_MANAGEMENT_API_TOKEN (server-only).</p>}
 {store&&configured&&<form action={startSupabaseProvisioning} className="mt-5 grid gap-3"><input type="hidden" name="store_id" value={store.id}/><input name="organization_slug" placeholder="Supabase organization slug" className="rounded-xl border border-white/10 bg-black/20 p-3" required/><div className="grid gap-3 sm:grid-cols-2"><select name="region_group" className="rounded-xl border border-white/10 bg-black/20 p-3"><option value="apac">APAC</option><option value="americas">Americas</option><option value="emea">EMEA</option></select><input name="db_password" type="password" minLength={24} placeholder="Unique DB password (24+ chars)" className="rounded-xl border border-white/10 bg-black/20 p-3" required/></div><button className="rounded-xl bg-white px-4 py-3 font-semibold text-black">Create / provision project</button></form>}
 {project&&<div className="mt-5 text-sm text-slate-400"><p>Status: {project.status} · Attempts: {project.attempt_count}</p>{project.project_ref&&<p className="mt-1">Project ref: {project.project_ref}</p>}{project.last_error&&<p className="mt-1 text-red-300">{project.last_error}</p>}{project.next_retry_at&&<p className="mt-1">Next retry: {new Date(project.next_retry_at).toLocaleString()}</p>}</div>}</div>
 {project&&project.status!=="ready"&&store&&<form action={processSupabaseProvisioning} className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-5 grid gap-3"><input type="hidden" name="store_id" value={store.id}/><input type="hidden" name="organization_slug" value={store.slug}/><input name="db_password" type="password" minLength={24} placeholder="DB password only if retrying project creation" className="rounded-xl border border-white/10 bg-black/20 p-3"/><p className="text-xs text-slate-500">Each run advances one provisioning step. Provider failures are persisted with exponential backoff.</p><button className="rounded-xl border border-white/10 px-4 py-2">Process next step</button></form>}
 </section>;
}