import {createSupabaseServerClient} from "@/lib/supabase/server";
import {addDomain,removeDomain,setPrimaryDomain,syncDomain} from "./actions";
export default async function DomainsPage(){
 const s=await createSupabaseServerClient();
 const {data:stores}=await s.from("stores").select("id,name,slug").order("created_at",{ascending:true}).limit(20);const store=stores?.[0];
 const {data:domains}=store?await s.from("domains").select("id,domain,kind,status,is_primary,provider_verified,dns_status,ssl_status,redirect_target,redirect_status_code,last_checked_at,verification").eq("store_id",store.id).order("created_at",{ascending:false}):{data:[]};
 const configured=Boolean(process.env.VERCEL_TOKEN);
 return <section className="p-5 sm:p-8"><h1 className="text-2xl font-bold">Custom Domains</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Connect a domain to the verified Vercel project, inspect DNS requirements, synchronize provider verification and manage the primary domain redirect.</p>
 <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Vercel domain integration</h2><p className="mt-1 text-sm text-slate-400">{configured?"Provider API configured":"VERCEL_TOKEN is missing"}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{configured&&domains?.some(d=>d.provider_verified)?"CONNECTED":"CONFIGURATION REQUIRED"}</span></div>
 {!configured&&<p className="mt-4 text-xs text-amber-300">Required: VERCEL_TOKEN (server-only).</p>}
 {store&&configured&&<form action={addDomain} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="store_id" value={store.id}/><input name="domain" placeholder="example.com" className="rounded-xl border border-white/10 bg-black/20 p-3"/><button className="rounded-xl bg-white px-4 py-2 font-semibold text-black">Add domain</button></form>}</div>
 <div className="mt-5 grid gap-4">{domains?.map(d=><article key={d.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{d.domain}</h2>{d.is_primary&&<span className="rounded-full bg-emerald-400/10 px-2 py-1 text-xs text-emerald-300">PRIMARY</span>}</div><p className="mt-1 text-xs text-slate-500">{d.kind} · checked {d.last_checked_at?new Date(d.last_checked_at).toLocaleString():"never"}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{d.status}</span></div>
 <div className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><div>DNS: <b>{d.dns_status}</b></div><div>Provider: <b>{d.provider_verified?"verified":"pending"}</b></div><div>SSL: <b>{d.ssl_status}</b></div></div>
 {d.verification&&Object.keys(d.verification).length>0&&<pre className="mt-4 overflow-auto rounded-xl bg-black/20 p-3 text-xs text-slate-400">{JSON.stringify(d.verification,null,2)}</pre>}
 {d.redirect_target&&<p className="mt-3 text-xs text-slate-400">Redirects to {d.redirect_target} ({d.redirect_status_code||308})</p>}
 <div className="mt-4 flex flex-wrap gap-2">{configured&&<form action={syncDomain}><input type="hidden" name="store_id" value={store?.id}/><input type="hidden" name="domain_id" value={d.id}/><button className="rounded-xl border border-white/10 px-3 py-2 text-sm">Sync verification</button></form>}{configured&&d.provider_verified&&!d.is_primary&&<form action={setPrimaryDomain}><input type="hidden" name="store_id" value={store?.id}/><input type="hidden" name="domain_id" value={d.id}/><button className="rounded-xl bg-cyan-300 px-3 py-2 text-sm font-semibold text-black">Set primary</button></form>}{configured&&!d.is_primary&&<form action={removeDomain}><input type="hidden" name="store_id" value={store?.id}/><input type="hidden" name="domain_id" value={d.id}/><button className="rounded-xl border border-red-400/30 px-3 py-2 text-sm text-red-300">Remove</button></form>}</div></article>)}</div>
 </section>;
}